# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: node:14.20.0

pipelines:
  branches:
    '{dev}': 
        - step:
            script:
              - apt-get update
              - apt-get install -y zip
              - npm install -g @angular/cli@14.2.11
              - npm install
              - ng build --configuration production --base-href=http://3.109.115.146/dev/
              - zip -r frontend.zip ./dist/sft-pms
              - pipe: atlassian/aws-code-deploy:0.2.10
                variables:
                  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                  APPLICATION_NAME: $APPLICATION_NAME
                  S3_BUCKET: $S3_BUCKET
                  COMMAND: 'upload'
                  ZIP_FILE: $ZIP_FILE
                  VERSION_LABEL: 'pms-dev-1.0.0'

              - pipe: atlassian/aws-code-deploy:0.2.10
                variables:
                  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                  APPLICATION_NAME: $APPLICATION_NAME
                  DEPLOYMENT_GROUP: $DEPLOYMENT_GROUP
                  S3_BUCKET: $S3_BUCKET
                  COMMAND: 'deploy'
                  WAIT: 'true'
                  VERSION_LABEL: 'pms-dev-1.0.0'
                  IGNORE_APPLICATION_STOP_FAILURES: 'true'
                  FILE_EXISTS_BEHAVIOR: 'OVERWRITE'